### ISSUE TITLE
Global parameters can have null descriptions (names)

### ISSUE THREAD

**Issue by cmutel** [pjamesjoyce/lcopt#12]
This is confusing (especially selecting them afterwards). It doesn't seem like it is editable afterwards, either.
Pop-up uses "Description", but table uses "Name".

**Comment by pjamesjoyce** [comment]
I've added some client side validation to stop users from being able to enter null values where they shouldn't. You now get a message telling you what you need to do.

I've also made is so IDs that can't be parsed are automatically changed to useable ones (e.g. `Useless Parameter!` --> `useless_parameter`)  and changed the form to refer to ID and Name instead of Name and Description.

**Comment by pjamesjoyce** [comment]
Link this issue to openjournals/joss-reviews#339
