### ISSUE TITLE
After clicking in the pie-chart (analise) to get the results - error 500 page

### ISSUE THREAD

**Issue by cdgaete** [pjamesjoyce/lcopt#23]
Hi I have installed lcopt according to the instruction given in http://lcopt.readthedocs.io
I have Ubuntu 17.10
I have created new env in conda, then I have imported ecoinvent3.3. It appeared True, that means the database was im[ported successfully. Then from the command line, with env activated, I type lcopt-launcher, then I choose open example model. Once the web app is opened I click in Analize in the in the tea cup box. I have waited for a while, the page error 500.

Here the log on the command line

(lcopt) carlos@Mapu:~/LinuxDisk/lca$ lcopt-launcher
Load example
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Created new window in existing browser session.
127.0.0.1 - - [26/Mar/2018 13:47:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:37] "GET /parameters HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:47:37] "GET /static/js/table-edit.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:47:37] "GET /static/css/parameter_table.css HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:47:38] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:15] "GET /settings HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:15] "GET /static/js/methods_box.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:48:15] "GET /static/css/methods_box.css HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:48:15] "GET /methods.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /results HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/cdn_cache/d3.min.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/cdn_cache/d3-legend.min.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/cdn_cache/d3-tip.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/cdn_cache/d3-textwrap.JJ.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/pie2.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/comparison_bar.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/css/analysis.css HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/css/treetest.css HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/result_table.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/treetest2.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/stacked_bar.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/export_chart.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /static/js/hotspot.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /results.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:21] "GET /results.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:23] "GET /settings HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:23] "GET /methods.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:23] "GET /functions HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:23] "GET /static/js/cdn_cache/selectize_duplicates_JJ.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:48:23] "GET /static/js/cdn_cache/selectize-plugin-clear.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:48:23] "GET /static/js/function_box.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:48:23] "GET /static/css/function_box.css HTTP/1.1" 304 -
127.0.0.1 - - [26/Mar/2018 13:48:24] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:24] "GET /parameters.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:24] "GET /parameters HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:25] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:26] "GET /functions HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:26] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:26] "GET /parameters.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:28] "GET /parameters HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:28] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:57] "GET /functions?preload=p_1_0 HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:58] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:58] "GET /parameters.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:58] "GET /parameter_p_1_0.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:48:58] "GET /parameter_p_1_0.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:20] "GET /parameters HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:21] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:23] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:32] "GET /status.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2018 13:50:32] "GET /analyse?item=Tea%20cup&item_code=e8e6f73b5bd401db0d553c80041d423f HTTP/1.1" 200 -
Created new bw2 project - Example Model
Writing database (Example Model_Database)...
Writing activities to SQLite3 database:
0%      100%
[##########] | ETA: 00:00:00
Total time elapsed: 00:00:00
Title: Writing activities to SQLite3 database:
  Started: 03/26/2018 13:50:37
  Finished: 03/26/2018 13:50:37
  Total time elapsed: 00:00:00
  CPU %: 0.00
  Memory %: 2.41
[2018-03-26 13:50:40,122] ERROR in app: Exception on /analysis [GET]
Traceback (most recent call last):
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/bw2data/backends/peewee/database.py", line 441, in process
    mapping[(input_database, input_code)],
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/bw2data/serialization.py", line 142, in __getitem__
    return self.data[key]
KeyError: ('Ecoinvent3_3_cutoff', '214da18debd3c0074df1c1996cf0fed4')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/lcopt/interact.py", line 884, in analysis
    self.modelInstance.analyse(item, item_code)
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/lcopt/model.py", line 790, in analyse
    self.result_set = my_analysis.run_analyses(demand_item, demand_item_code, **self.analysis_settings)
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/lcopt/analysis.py", line 165, in run_analyses
    new_db.write(self.bw2_database)
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/bw2data/project.py", line 366, in writable_project
    return wrapped(*args, **kwargs)
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/bw2data/backends/peewee/database.py", line 269, in write
    self.process()
  File "/home/carlos/app/ana3/envs/lcopt/lib/python3.6/site-packages/bw2data/backends/peewee/database.py", line 463, in process
    (output_database, output_code)
bw2data.errors.UnknownObject: Exchange between ('Ecoinvent3_3_cutoff', '214da18debd3c0074df1c1996cf0fed4') and ('Example Model_Database', '0c73790b049c24afce18d62d869068a6') is invalid - one of these objects is unknown (i.e. doesn't exist as a process dataset)
127.0.0.1 - - [26/Mar/2018 13:50:40] "GET /analysis?item=Tea%20cup&item_code=e8e6f73b5bd401db0d553c80041d423f HTTP/1.1" 500 -

**Comment by pjamesjoyce** [comment]
Hi @cdgaete 

I think I know what might be causing this, but I need to ask you to run something to check if that's ok?

lcopt is only currently compatible with the ecoinvent 3.3 **cutoff** database. If you've set it up with another version of ecoinvent (e.g. 3.3 APOS or 3.4 cutoff) it won't function properly. I'm in the process of figuring out how to allow different versions of ecoinvent to be used at the moment, but the example model uses 3.3 cutoff.

### If you know you used a different version of ecoinvent, try the following:

*Note - this is using a jupyter notebook for ease, if you're more comfortable using a regular python shell in the terminal feel free.*

1. Download the 3.3 cutoff version of ecoinvent from [ecoinvent.org](https://www.ecoinvent.org/login-databases.html) - the file should be called `ecoinvent 3.3_cutoff_ecoSpold02.7z`
2. Unzip the .7z file and make a note of the path of the 'datasets' folder
3. Activate your lcopt environment at the command line/terminal
4. `cd` somewhere you don't mind creating new files (jupyter notebook .ipynb files) e.g. My Documents - you can always delete them later
5. Type `jupyter notebook` at the terminal to open up the jupyter notebook console in your browser
6. Create a new jupyter workbook
7. Run the following lines of code to overwrite the LCOPT_Setup bw2 project:

```python
from lcopt.utils import lcopt_bw2_setup

ecospold_path = r"put/the/path/of/the/datasets/folder/here" # <-- the path goes here

lcopt_bw2_setup(ecospold_path, overwrite=True)
```
This will overwrite the existing version of the LCOPT_Setup project in brightway2 with a version containing ecoinvent3.3cutoff.

8. In the same Jupyter notebook (or a different one if you prefer) run the following code to delete the old version of the 'Example Model' bw2 database that was created with the wrong version of ecoinvent

```python
from brightway2 import *
projects.delete_project(name="Example Model", delete_dir=True)
```
9. Close the jupyter notebook, and press Ctrl+C in the terminal window to shut down the notebook console.

10. Use `lcopt-launcher` to try the example model again and let me know if that fixes it.


### If you don't know which version of ecoinvent you imported, try this:

1. Open up a jupyter notebook as described above (or a python shell).
2. Run the following code:
```python
from brightway2 import *
projects.set_current('LCOPT_Setup')
db = Database('Ecoinvent3_3_cutoff')
milk = db.search('cow milk GLO market')[0]
print("{}\n\n{}".format(milk['name'],milk['filename']))
```
This should print `market for cow milk` and then on another line a long string of letters, numbers and hyphens representing the dataset filename. Like this:
```
market for cow milk

98c6a35d-80bb-4a23-b11e-68688a93b7b4_a3ee1ec6-ce17-430e-a475-f98f1b2890d2.spold
```

If it doesn't, let me know...

3. Check the first 8 characters of the dataset filename against the table below:

|First 8 characters| Database|
|------------------|------------|
|**98c6a35d** |**ecoinvent 3.3 cutoff**|
|d46da0e3 | ecoinvent 3.3 apos|
|fec55b30 | ecoinvent 3.4 cutoff|

If it turns out you're not using ecoinvent 3.3 cutoff, download it and run the overwrite procedure above.

If you **are** using ecoinvent 3.3 cutoff something else has gone wrong...

Let me know how you get on

James

**Comment by cdgaete** [comment]
Thank you very much, I was using eco 34, I have followed all the steps you suggested and now is working perfectly! I am starting learning this app. Really, interesting and useful!
